# 개선된 워크플로우
name: Docker - v2

on:
  push:
    paths:
      - .github/workflows/v2.yaml
      - '2.2/**'
      - '2.3/**'

env:
  AWS_REGION: us-east-1
  ECR_REPO: public.ecr.aws/u0u1j5s3/composer

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        version: [2.2, 2.3]
    defaults:
      run:
        working-directory: ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Build Args
        id: build_args
        run: |
          if [ "${{ matrix.version }}" == "2.2" ]; then
            VERSION_TAG=$(grep -oE 'COMPOSER_VERSION 2.2.[\d]+' Dockerfile | grep -oE '2.2.[\d]+')
          else
            VERSION_TAG=$(grep -oE 'COMPOSER_VERSION 2.3.[\d]+(-RC[\d])?' Dockerfile | grep -oE '2.3.[\d]+(-RC[\d])?')
          fi
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build \
          --pull \
          --no-cache \
          --tag composer/composer:latest \
          --tag composer/composer:2 \
          --tag composer/composer:${{ env.VERSION_TAG }} \
          .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push tag(s) to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push composer/composer:latest
          docker push composer/composer:2
          docker push composer/composer:${{ env.VERSION_TAG }}

      - name: Login to Amazon Public ECR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          password: ${{ secrets.AWS_ECR_SECRET_KEY }}

      - name: Push tag(s) to Amazon Public ECR
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag composer/composer:latest $ECR_REPO:latest
          docker tag composer/composer:2 $ECR_REPO:2
          docker tag composer/composer:${{ env.VERSION_TAG }} $ECR_REPO:${{ env.VERSION_TAG }}
          docker push $ECR_REPO:latest
          docker push $ECR_REPO:2
          docker push $ECR_REPO:${{ env.VERSION_TAG }}

  # Prevent running workflows on older commits
  concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true