# 개선된 워크플로우
name: Trigger Jenkins Job Workflow

on:
  push:
    branches:
      - main
    # 최신 커밋이 있을 때만 워크플로우를 실행하도록 설정
    paths:
      - '**/*'  # 모든 파일이 변경되었을 때만 실행

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 타임아웃 설정

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://ec2-18-181-186-207.ap-northeast-1.compute.amazonaws.com/"
          user: "illasoft"
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: "illa-builder-test"