# 개선된 워크플로우
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: 
      image: centos:7
      options: --privileged

    env: 
      PGDATA: /tmp/pgdata

    timeout-minutes: 30  # 작업에 대한 타임아웃 설정 추가

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        mkdir -p $PGDATA
        yum install -y gcc gcc-c++ make python3 postgresql-server git
        curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
        python3 get-pip.py --user
        python3 -m pip install awscli cmake --upgrade --user

    - name: Setup Postgres
      run: |
        systemctl start postgresql

    - name: Update DuckDB submodule
      run: |
        git submodule init
        git submodule update --remote --merge

    - name: Build
      run: |
        export PATH=/github/home/.local/bin:$PATH
        make release

    - name: Make test databases
      run: |
        ./create-postgres-tables.sh

    - name: Test
      run: |
        ./duckdb/build/release/test/unittest --test-dir . "[postgres_scanner]"
        ./build/release/concurrency_test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: postgres-scanner
        path: |
          build/release/postgres_scanner.duckdb_extension