# 개선된 워크플로우
name: Update translation files

on: [workflow_dispatch]

jobs:
  build-linux:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    timeout-minutes: 10  # 작업에 대한 타임아웃 설정 추가

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'

      - name: Run lupdate
        run: lupdate src/NotepadNext.pro

      - name: Commit translation changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update translation files
          file_pattern: 'i18n/*.ts'
          branch: main  # 커밋할 브랜치 명시 (기본값은 'main'으로 설정)

      - name: Push changes
        run: git push origin main  # 변경 사항을 원격 저장소에 푸시