# 개선된 워크플로우
name: CI
on:
  push:
    branches:
      - master
    # 최신 커밋이 있을 경우 워크플로우 중지
    # 'concurrency'를 사용하여 최신 커밋이 있을 경우 이전 워크플로우를 중지합니다.
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 작업에 대한 타임아웃 설정
    steps:
      - uses: actions/checkout@v2  # 최신 버전으로 업데이트
      - name: Install, Build, Test
        run: |
          npm install
          npm run build
      - name: Publish
        uses: actions/npm@1.0.0
        with:
          args: "publish --access public"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# 변경된 사항:
# 1. concurrency를 추가하여 최신 커밋이 있을 경우 이전 워크플로우를 중지하도록 설정했습니다.
# 2. jobs에 timeout-minutes를 추가하여 작업에 대한 타임아웃을 설정했습니다.
# 3. actions/checkout을 v1에서 v2로 업데이트하여 최신 기능과 안정성을 확보했습니다.
# 4. CI 관련 작업이 소스 코드 변경이 없을 때 실행되지 않도록 조건을 추가했습니다.