# 개선된 워크플로우
name: Publish to Pub.dev

on:
  push:
    branches:
      - main  # 특정 브랜치에 대한 푸시 이벤트만 트리거
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 작업에 대한 타임아웃 설정

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2  # 최신 버전으로 업데이트

      - name: Set up Dart
        run: pub get  # 의존성 설치

      - name: Copy required files
        run: |
          cp ../README.md README.md
          cp ../LICENSE LICENSE

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected"  # 변경 사항 확인

      - name: Publish to Pub.dev
        if: steps.check_changes.outputs.changed == 'true'  # 변경 사항이 있을 때만 실행
        run: pub publish --dry-run
        working-directory: ./mapper