# 개선된 워크플로우
name: Dart

on:
  push:
    branches: [ master ]
    # 최신 커밋이 있을 경우 워크플로우를 중단하도록 설정
    if: github.event.head_commit.id != github.event.before
  pull_request:
    branches: [ master ]
    # 최신 커밋이 있을 경우 워크플로우를 중단하도록 설정
    if: github.event.pull_request.head.sha != github.event.before

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 타임아웃 설정

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
      
      # facebook_auth 패키지의 변경 사항이 있을 경우에만 실행
      - name: Install facebook_auth dependencies 
        run: |
          cd facebook_auth
          flutter pub get
        if: steps.check_changes.outputs.facebook_auth_changed == 'true'

      - name: Run facebook_auth tests --coverage
        run: |
          cd facebook_auth
          flutter test
        if: steps.check_changes.outputs.facebook_auth_changed == 'true'

      # facebook_auth_platform_interface 패키지의 변경 사항이 있을 경우에만 실행
      - name: Install facebook_auth_platform_interface dependencies 
        run: |
          cd facebook_auth_platform_interface
          flutter pub get
        if: steps.check_changes.outputs.facebook_auth_platform_interface_changed == 'true'

      - name: Run facebook_auth_platform_interface tests --coverage
        run: |
          cd facebook_auth_platform_interface
          flutter test
        if: steps.check_changes.outputs.facebook_auth_platform_interface_changed == 'true'

      # facebook_auth_web 패키지의 변경 사항이 있을 경우에만 실행
      - name: Install facebook_auth_web dependencies 
        run: |
          cd facebook_auth_web
          flutter pub get
        if: steps.check_changes.outputs.facebook_auth_web_changed == 'true'

      - name: Run facebook_auth_web tests --coverage
        run: |
          cd facebook_auth_web
          flutter test --platform chrome
        if: steps.check_changes.outputs.facebook_auth_web_changed == 'true'

      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1 
        with: 
          file: facebook_auth_platform_interface/coverage/lcov.info

      # 변경 사항 체크를 위한 단계
      - name: Check for changes
        id: check_changes
        run: |
          echo "::set-output name=facebook_auth_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'facebook_auth/' && echo 'true' || echo 'false')"
          echo "::set-output name=facebook_auth_platform_interface_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'facebook_auth_platform_interface/' && echo 'true' || echo 'false')"
          echo "::set-output name=facebook_auth_web_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'facebook_auth_web/' && echo 'true' || echo 'false')"