name: Create YAML on direct push to README

on:
  push:
    paths:
      - "README.md"

jobs:
  create_yamls:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 작업에 대한 타임아웃 설정
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install pyyaml

      - name: Execute Python script to create YAMLs
        run: python create_yamls.py

    # 최신 커밋이 있을 경우 워크플로우 중단
    if: github.event.before != github.sha