on:
  pull_request: {}
name: Test
jobs:
  test:
    name: Test
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ['15.2']
    steps:
      - name: Stop if there are newer commits
        uses: actions/github-script@v6
        id: check_commits
        with:
          script: |
            const { data: { head: { sha: headSha } } } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            if (headSha !== '${{ github.event.pull_request.head.sha }}') {
              throw new Error('There are newer commits in the PR. Stopping the workflow.');
            }

      - name: Set Xcode ${{ matrix.xcode }}
        run: |
          echo "Available Xcode versions:"
          ls /Applications | grep Xcode
          echo "Choosing Xcode_${{ matrix.xcode }}.app"
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
          xcodebuild -version
          swift --version
          swift package --version
        timeout-minutes: 10

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mise
        run: |
          curl https://mise.jdx.dev/install.sh | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
        timeout-minutes: 10

      - name: Install & Run tuist
        run: |
          touch .env
          echo "APP_NAME=Keyboard Cowboy" >> .env
          echo "APP_SCHEME=Keyboard-Cowboy" >> .env
          echo "APP_BUNDLE_IDENTIFIER=com.zenangst.Keyboard-Cowboy" >> .env
          echo "TEAM_ID=XXXXXXXXXX" >> .env
          echo "PACKAGE_DEVELOPMENT=false" >> .env
          tuist fetch
          tuist generate -n
        timeout-minutes: 10

      - name: Run tests
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: "Keyboard Cowboy.xcworkspace"
          scheme: "Keyboard-Cowboy"
          destination: platform=macOS
          action: test
          result-bundle-path: ResultBundle.xcresult
          sdk: macosx
          build-settings: CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO"
        timeout-minutes: 30

      - name: xcresulttool
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: ResultBundle.xcresult
        timeout-minutes: 10

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: ResultBundle.xcresult
        timeout-minutes: 10

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}\n\n@${{ github.event.pull_request.user.login }}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });