# 개선된 워크플로우
name: Deploy mdBook to GCS

on:
  push:
    branches:
      - main 
      - jolt
    # 최신 커밋이 있을 경우 워크플로우를 중단하도록 설정
    # 'if' 조건을 사용하여 최신 커밋이 아닐 경우 실행하지 않도록 함
    paths-ignore:
      - '**.md'  # 예시: md 파일이 변경되지 않은 경우 무시

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 작업에 대한 타임아웃 설정

    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'

    - name: Install mdbook-katex
      run: cargo install mdbook-katex

    - name: Build mdBook
      run: mdbook build ./book

    - name: Deploy to Google Cloud Storage
      run: gsutil -m rsync -d -r ./book/book gs://${{ secrets.GCS_BUCKET_NAME }}