---

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run at 1:00 every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pip-version: ['==21.2.4', '']
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Avoid fetching all history for faster performance

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade 'pip ${{ matrix.pip-version }}'
          python -m pip install --ignore-installed --editable .[dev]
          python -m pip install flake8

      - name: "Lint"
        run: |
          flake8 *.py pip_check_reqs tests
          pip-extra-reqs pip_check_reqs
          pip-missing-reqs pip_check_reqs

      - name: "Run tests"
        run: |
          pytest -s -vvv --cov-fail-under 100 --cov=pip_check_reqs/ --cov=tests tests/ --cov-report=xml

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3"

    timeout-minutes: 30  # Avoid jobs without timeouts

    # Prevent running workflows on forks for scheduled events
    if: github.event_name != 'schedule' || github.repository == 'your-username/your-repo'

    # Prevent running CI actions if no source code has changed
    if: ${{ github.event_name != 'push' || github.event.changes }}