# 개선된 워크플로우
name: Hook Slinger Build & Test

on:
  push:
    branches:
      - main
    # 최신 커밋이 있을 경우 워크플로우 중단
    paths-ignore:
      - '**/*' # 소스 코드 변경이 없을 경우 워크플로우를 실행하지 않음
  pull_request:
    branches:
      - main
    # 최신 커밋이 있을 경우 워크플로우 중단
    paths-ignore:
      - '**/*' # 소스 코드 변경이 없을 경우 워크플로우를 실행하지 않음

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # 작업에 대한 타임아웃 설정
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        run: |
          python -m pip install --upgrade pip
          pip install docker-compose

      - name: Run the Linters, Build the Containers & Run the Tests
        run: make start_tests

      - name: Check Test Log
        run: |
          docker logs -f hook-slinger_test_1