# 개선된 워크플로우
name: Publish

# Trigger the workflow's on pushed tags or commits to main/master branch.
on:
  push:
    branches: 
      - main
      - master
    tags: 
      - '*'  # 모든 태그에 대해 트리거
    paths:
      - '**/*'  # 소스 코드가 변경된 경우에만 트리거

defaults:
  run:
    shell: bash

jobs:
  Publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 작업 타임아웃 설정
    if: github.event.head_commit.timestamp == github.event.before  # 최신 커밋이 없을 경우 실행하지 않음
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install chart publishing dependencies (chartpress, helm)
        run: |
          . ./ci/common
          setup_helm
          pip install --no-cache-dir chartpress

      - name: Setup push rights to jupyterhub/helm-chart
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.JUPYTERHUB_HELM_CHART_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Setup push rights to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Configure a git user
        run: |
          git config --global user.email "github-actions@example.local"
          git config --global user.name "GitHub Actions user"

      - name: Publish images and chart with chartpress
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
        run: |
          ./ci/publish