name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_OPTIONS: --max-old-space-size=6144

permissions:
  contents: read

jobs:
  release-pr:
    permissions:
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 최신 커밋을 가져오기 위해 fetch-depth 설정

      - run: corepack enable
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code HEAD^ HEAD -- || echo "changes=true" >> $GITHUB_ENV

      - name: Build Stub
        if: env.changes == 'true'  # 소스 코드 변경이 있을 때만 실행
        run: pnpm build:stub

      - name: Build
        if: env.changes == 'true'  # 소스 코드 변경이 있을 때만 실행
        run: pnpm build:ci

      - name: Release Edge
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]') &&
          env.changes == 'true'  # 소스 코드 변경이 있을 때만 실행
        run: ./scripts/release-edge.sh pr-${{ github.event.issue.number }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true