name: CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'  # 소스 코드가 변경된 경우에만 CI 실행
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # GitHub Token 사용 시 권한 설정
      contents: read
      actions: read
      checks: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt
      - name: Test and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage run -m pytest 
          coverage run -a ./update.py --release
      - name: Report coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          coverage xml
          coverage report
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter after-build

    timeout-minutes: 30  # 작업 타임아웃 설정