name: CI Workflow
on: [push]

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Added timeout to avoid jobs without timeouts
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://ec2-18-181-186-207.ap-northeast-1.compute.amazonaws.com/"
          user: "illasoft"
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: "illa-builder-test"