# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
    # Stop running workflows when there is a newer commit in branch
    # This prevents unnecessary runs for the same commit
    if: github.event.head_commit.id == github.sha
  pull_request:
    branches:
      - master
    # Stop running workflows when there is a newer commit in PR
    # This prevents unnecessary runs for the same commit
    if: github.event.pull_request.head.sha == github.sha

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: CI='' && npm run build --if-present
      - run: touch ./build/.nojekyll
      - run: sed -i 's|scran/scran|kana/scran/scran|g' ./build/scran/scran.js
      - name: GH Pages Deployment
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: github.ref == 'refs/heads/master' # 수정된 부분
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./build
          clean: true # Automatically remove deleted files from the deploy branch
      - name: Set timeout for job
        run: |
          echo "Setting timeout for the job"
        timeout-minutes: 10 # Avoid jobs without timeouts
      - name: Check for changes before running CI
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected, skipping CI related actions."
            exit 0
          fi