name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened] # Stop running workflows when there is a newer commit in PR
  push:
    branches:
      - main # Stop running workflows when there is a newer commit in branch

jobs:
  build-and-test:
    name: build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 30 # Avoid jobs without timeouts
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: nix-script
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build --print-build-logs

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Avoid jobs without timeouts
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: nix-script
          skipPush: true

      - run: nix develop --command rustfmt --check $(find . -name "*.rs" -not -ipath '*target*')

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Avoid jobs without timeouts
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: nix-script
          skipPush: true

      - run: nix develop --command cargo clippy -- --deny warnings