name: CI

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - '**.md'  # Avoid running CI related actions when no source code has changed
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Avoid jobs without timeouts
    permissions:  # Use permissions whenever using Github Token
      contents: read
      actions: read
      checks: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt
      - name: Test && Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage run -m pytest 
          coverage run -a ./update.py --release
      - name: Report coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          coverage xml && coverage report
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter after-build