name: Main Workflow
on: [push]
jobs:
  build-py2:
    name: Build Python 2.7
    runs-on: ubuntu-latest
    container: python:2.7
    steps:
      - uses: actions/checkout@v2  # v1에서 v2로 업데이트
      - run: python --version
      - run: pip install -r requirements.txt
      - run: pip install -r extra.txt
      - run: ADAPTER=tiny HTTPBIN=httpbin.bemisc.com python setup.py test

  build-py3-6:  # 중복된 키를 수정하여 고유한 이름으로 변경
    name: Build Python 3.6
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
      - uses: actions/checkout@v2  # v1에서 v2로 업데이트
      - run: python3 --version
      - run: pip3 install -r requirements.txt
      - run: pip3 install -r extra.txt
      - run: ADAPTER=tiny HTTPBIN=httpbin.bemisc.com python3 setup.py test

  build-py3-7:  # 중복된 키를 수정하여 고유한 이름으로 변경
    name: Build Python 3.7
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - uses: actions/checkout@v2  # v1에서 v2로 업데이트
      - run: python3 --version
      - run: pip3 install -r requirements.txt
      - run: pip3 install -r extra.txt
      - run: ADAPTER=tiny HTTPBIN=httpbin.bemisc.com python3 setup.py test