name: Protobuf Janitor

on:
  schedule:
    # Run daily at 10 AM UTC (2 AM PDT)
    - cron: 0 10 * * *
  workflow_dispatch:

jobs:
  stale-prs:
    name: Close Stale Copybara PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # 필요한 권한 설정
    timeout-minutes: 10  # 작업 타임아웃 설정
    steps:
      - name: Close stale PRs
        run: |
          set -ex
          STALE_PRS=$(gh pr list --author "app/copybara-service" --limit 500 \
              --json "number" --search "updated:<=$(date --date="-7 day" +%F)" \
            | jq ".[].number")
          for pr in $STALE_PRS; do
            echo "Closing #$pr..."
            gh pr close --comment "Auto-closing Copybara pull request" --delete-branch "$pr"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}