name: ðŸ¹Sponsor video generator
on:
  workflow_dispatch:
    inputs:
      companyName:
        description: "What is the name of the sponsor company?"
        required: true
        default: "Example"
      backgroundImg:
        description: "If you want to use custom image for background"
        required: false

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    timeout-minutes: 30  # ìž‘ì—… íƒ€ìž„ì•„ì›ƒ ì¶”ê°€
    steps:
      - name: Update package list
        run: sudo apt update
      
      - name: Install ffmpeg
        run: sudo apt install -y ffmpeg  # -y í”Œëž˜ê·¸ ì¶”ê°€ë¡œ ìžë™ ì„¤ì¹˜
      
      - name: Checkout repository
        uses: actions/checkout@v2  # ì•ˆì •ì ì¸ ë²„ì „ìœ¼ë¡œ ë³€ê²½
      
      - name: Setup Node.js
        uses: actions/setup-node@v3  # ìµœì‹  ë²„ì „ìœ¼ë¡œ ë³€ê²½
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: true
      
      - name: Create input properties JSON
        run: echo "${{ toJson(github.event.inputs) }}" > input-props.json
      
      - name: Render video
        run: pnpm remotion render src/index.tsx Sponsor out/sponsor-${{ github.event.inputs.companyName }}.mp4 --props="./input-props.json"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3  # ìµœì‹  ë²„ì „ìœ¼ë¡œ ë³€ê²½
        with:
          name: sponsor-${{ github.event.inputs.companyName }}
          path: out