name: ci

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: ${{ matrix.language }} on ${{ matrix.os }}
    strategy:
      matrix:
        language: [cpp]
        os: [macos-latest, macos-13, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            language: swift
          - os: macos-latest
            language: objective-c
          - os: macos-latest
            language: python
          - os: macos-latest
            language: php
          - os: macos-latest
            language: ruby
          - os: ubuntu-latest
            language: csharp
          - os: ubuntu-latest
            language: java
          - os: ubuntu-latest
            language: php
          - os: ubuntu-latest
            language: ruby
          - os: ubuntu-latest
            language: python
          - os: ubuntu-latest
            language: js
          - os: windows-latest
            language: python

      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90  # 전체 job에 대한 timeout 설정
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Build ${{ matrix.language }} on ${{ matrix.os }}
        uses: ./.github/actions/build

      - name: Test ${{ matrix.language }} on ${{ matrix.os }}
        uses: ./.github/actions/test
        with:  # inputs를 with로 변경
          flags: "--rfilter IceGrid/replication"