name: Prerelease

on:
  push:
    branches:
      - "master"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'chore(release): packages')"
    timeout-minutes: 30  # Avoid jobs without timeouts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: yarn cache directory
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Setup node_modules cache
        uses: actions/cache@v2  # Updated to the latest version
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v2  # Updated to the latest version
        with:
          node-version: ${{ env.NVMRC }}
          registry-url: https://registry.npmjs.org/
          scope: flopflip

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Publish to next dist-tag
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          yarn release:next