name: Hook Slinger Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          pip install docker-compose
          make start_tests

      - name: Check Test Log
        run: |
          docker logs -f hook-slinger_test_1