name: Publish

# Trigger the workflow's on pushed tags or commits to main/master branch.
on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  Publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Avoid jobs without timeouts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install chart publishing dependencies (chartpress, helm)
        run: |
          . ./ci/common
          setup_helm
          pip install --no-cache-dir chartpress

      - name: Setup push rights to jupyterhub/helm-chart
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.JUPYTERHUB_HELM_CHART_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Setup push rights to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Configure a git user
        run: |
          git config --global user.email "github-actions@example.local"
          git config --global user.name "GitHub Actions user"

      - name: Publish images and chart with chartpress
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
        run: |
          ./ci/publish