name: release

on:
  push:
    branches:
      - main
    # 최신 커밋이 있을 경우 워크플로우를 중단
    if: github.event.after != github.event.before
  pull_request:
    branches:
      - main
    # 최신 커밋이 있을 경우 워크플로우를 중단
    if: github.event.after != github.event.before

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  NODE_OPTIONS: --max-old-space-size=6144

permissions:
  contents: read

jobs:
  release-pr:
    permissions:
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 최신 버전으로 업데이트

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Stub
        run: pnpm build:stub

      - name: Build
        run: pnpm build:ci

      - name: Release Edge
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]')
        run: ./scripts/release-edge.sh pr-${{ github.event.number }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true